# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DXF_Splitter
                                 A QGIS plugin
 Splits and exports DXF into shapefiles and geopackage.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-20
        copyright            : (C) 2026 by Krishna Kunnampully
        email                : zankrish@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Krishna Kunnampully'
__date__ = '2026-01-20'
__copyright__ = '(C) 2026 by Krishna Kunnampully'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DXF_Splitter class from file DXF_Splitter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DXF_Splitter import DXF_SplitterPlugin
    return DXF_SplitterPlugin(iface)
