# -*- coding: utf-8 -*-

"""
/***************************************************************************
 DXF_Splitter
                                 A QGIS plugin
 Splits and exports DXF into shapefiles and geopackage.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-20
        copyright            : (C) 2026 by Krishna Kunnampully
        email                : zankrish@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Krishna Kunnampully'
__date__ = '2026-01-20'
__copyright__ = '(C) 2026 by Krishna Kunnampully'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFolderDestination,
                       QgsProcessingParameterFile,
                       QgsVectorLayer,
                       QgsVectorFileWriter,
                       QgsProject,
                       QgsWkbTypes,
                       QgsProcessingContext,
                       QgsProcessingParameterBoolean,
                       QgsProcessingOutputLayerDefinition,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterString,
                       QgsProcessingException,
                       QgsProcessingParameterCrs,
                       QgsProcessingParameterCoordinateOperation)


class DXF_SplitterAlgorithm(QgsProcessingAlgorithm):
    

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    
    INPUT = 'INPUT'
    OUTPUT_FOLDER = 'OUTPUT_FOLDER'
    LOAD_TO_PROJECT = 'LOAD_TO_PROJECT'
    EXPORT_FORMAT = 'EXPORT_FORMAT'
    GPKG_NAME = 'GPKG_NAME'
    TARGET_CRS = 'TARGET_CRS'

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(QgsProcessingParameterFile(self.INPUT,'Input DXF file',extension='dxf'))
        self.addParameter(QgsProcessingParameterFolderDestination(self.OUTPUT_FOLDER,'Output folder for shapefiles'))
        self.addParameter(QgsProcessingParameterBoolean(self.LOAD_TO_PROJECT,'Load exported layers to the Project',defaultValue=False))
        self.addParameter(QgsProcessingParameterEnum('EXPORT_FORMAT','Export Format', options=['Seperate SHP files', 'Seperate GPKG files','Single GPKG','Grouped by Geometry (Geopackage)', 'Grouped by Geometery (Shapefiles)'], defaultValue=0))
        self.addParameter(QgsProcessingParameterString('GPKG_NAME','GeoPackage Name (if applicable)', defaultValue='output.gpkg', optional=True))
        self.addParameter(QgsProcessingParameterCrs(self.TARGET_CRS,'Target CRS'))
       

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        input_path = parameters[self.INPUT]
        output_folder = parameters[self.OUTPUT_FOLDER]
        load_to_project = parameters.get(self.LOAD_TO_PROJECT,True)
        export_format = parameters[self.EXPORT_FORMAT]
        gpkg_name = parameters.get(self.GPKG_NAME,'output.gpkg')
        gpkg_path = os.path.join(output_folder, gpkg_name)
        
        # Load DXF as a vector layer
        layer = QgsVectorLayer(input_path, 'DXF Layer', 'ogr')
        if not layer.isValid():
            raise Exception('Failed to load DXF file.')

        # Read selected Target CRS
        target_crs = self.parameterAsCrs(parameters, self.TARGET_CRS, context)
        src_crs = layer.sourceCrs()
        
        # Group features by geometry type and layer name
        groups = {}
        for feature in layer.getFeatures():
           geom_str = QgsWkbTypes.displayString(feature.geometry().wkbType())
           layer_name = feature.attribute('Layer')
           key = (layer_name,geom_str)
           if export_format == (3,4): # Grouped by Geometry
              key = geom_str
           if key not in groups:
                groups[key] = []
           groups[key].append(feature)
           
        otps = QgsVectorFileWriter.SaveVectorOptions()

        # Create and save shapefiles
        for key, features in groups.items():
            if export_format == 3 or export_format == 4: # Grouped by Geometry
              layer_name = key
              geom_str = key
            else:
              layer_name, geom_type = key
              geom_str = {
                'Point': 'PT',
                'LineString': 'L',
                'Polygon': 'PN',
                'PointZ': 'PT',
                'LineStringZ': 'L',
                'MultiLineStringZ': 'L',
                'PolygonZ': 'PN',
                'MultiPolygonZ': 'PN'
            }.get(geom_type, 'UNK')
    
            
            
            # Determine output path and format
            if export_format == 0: # seperate SHP
               output_path = os.path.join(output_folder,f"{layer_name}_{geom_str}.shp")
               otps.driverName = 'ESRI Shapefile'
            elif export_format == 1: # seperate GPKG
               output_path = os.path.join(output_folder, f"{layer_name}_{geom_str}.gpkg")
               otps.driverName = 'GPKG'
            elif export_format == 2: # single GPKG
               output_path = gpkg_path
               otps.driverName = 'GPKG'
            elif export_format == 3: # Grouped by Geometry (geopackage)
               output_path = os.path.join(output_folder, f"{geom_str}.gpkg")
               otps.driverName = 'GPKG'
               otps.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
            elif export_format == 4: # Grouped by Geometry (shapefiles)
               output_path = os.path.join(output_folder, f"{geom_str}.shp")
               otps.driverName = 'ESRI Shapefile'
            else:
                raise QgsProcessingException('Invalid export format.')
                
            fields = layer.fields()
            transform_context = QgsProject.instance().transformContext()
            if otps.driverName == 'GPKG':
               otps.layerName = f"{layer_name}_{geom_str}"
            
            geometry_type = features[0].geometry().wkbType()
            writer = QgsVectorFileWriter.create(
            output_path,
            fields,
            geometry_type,
            target_crs,
            transform_context,
            otps
            )

            for feature in features:
                writer.addFeature(feature)

            del writer
            
            # optionally load the exported layer into the project
            if load_to_project:
                exported_layer = QgsVectorLayer(output_path, otps.layerName if otps.driverName == 'GPKG' else f"{layer_name}_{geom_str}", 'ogr')
                if exported_layer.isValid():
                    QgsProject.instance().addMapLayer(exported_layer)
                    feedback.pushInfo(f"Loaded layer: {exported_layer.name()}")
                else:
                    feedback.reportError(f"Exported layer is invalid: {output_path}")
                

        return {self.OUTPUT_FOLDER: output_folder}


        

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'DXF_Splitter'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('DXF Splitter')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'CAD_Tools'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DXF_SplitterAlgorithm()
